# Generated by Django 5.0.6 on 2024-08-07 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='picture',
            field=models.ImageField(blank=True, default='default-profile-pic.png', upload_to='profile_pictures/'),
        ),
    ]
