# Generated by Django 5.0.6 on 2024-08-07 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='picture',
        ),
    ]
