# Generated by Django 5.0.6 on 2024-08-03 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Double Deluxe', 'Double Deluxe Room'), ('Single Deluxe', 'Single Deluxe Room'), ('Honeymoon Suite', 'Honeymoon Suite'), ('Economy Double', 'Economy Double')], max_length=50)),
                ('price_per_night', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
    ]
