# Generated by Django 5.0.6 on 2024-08-04 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='price_per_room',
            field=models.DecimalField(decimal_places=2, default='2.0', max_digits=10),
            preserve_default=False,
        ),
    ]
