# Generated by Django 5.0.6 on 2024-08-04 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_booking_price_per_room'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='price_per_room',
            new_name='price_per_night',
        ),
        migrations.AddField(
            model_name='booking',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=2.0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='booked_at',
            field=models.DateTimeField(),
        ),
    ]
