# Generated by Django 5.0.6 on 2024-08-05 05:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_availability'),
    ]

    operations = [
        migrations.RenameField(
            model_name='availability',
            old_name='date',
            new_name='end_date',
        ),
        migrations.AddField(
            model_name='availability',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='availability',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
