# Generated by Django 5.0.6 on 2024-08-07 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_rename_date_availability_end_date_availability_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='type',
            field=models.CharField(choices=[('Double Deluxe', 'Double Deluxe Room'), ('Double Standard', 'Double Standard Room'), ('Honeymoon Suite', 'Honeymoon Suite'), ('Economy Double', 'Economy Double')], max_length=50),
        ),
    ]
