# Generated by Django 5.0.6 on 2024-08-07 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0007_alter_room_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('in_cart', 'In Cart'), ('completed', 'Completed')], default='in_cart', max_length=20),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booked_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
